version: '3'
services:
  android-emulator:
    build: .
    ports:
      - "5554:5554"
      - "5555:5555"
      - "5900:5900"
      - "6080:6080"
    volumes:
      - ./sdk:/opt/android-sdk-linux
    environment:
      - ANDROID_HOME=/opt/android-sdk-linux